// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeAp p(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5xq7KBhFYW-B7TywmFVMiurp_guBPB84',
    appId: '1:540397899968:web:71b195bf0e173dde22dd25',
    messagingSenderId: '540397899968',
    projectId: 'sakkokassa-15fec',
    authDomain: 'sakkokassa-15fec.firebaseapp.com',
    storageBucket: 'sakkokassa-15fec.appspot.com',
    measurementId: 'G-WVW67FFM9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnCeGDfEfgSJuEr9OanL99Kg3seeZfw4',
    appId: '1:540397899968:android:f58e016f809c547422dd25',
    messagingSenderId: '540397899968',
    projectId: 'sakkokassa-15fec',
    storageBucket: 'sakkokassa-15fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8s4m66v2n4EUHfNSckm8H7T-d-uYfJpU',
    appId: '1:540397899968:ios:5184e866646c458322dd25',
    messagingSenderId: '540397899968',
    projectId: 'sakkokassa-15fec',
    storageBucket: 'sakkokassa-15fec.appspot.com',
    iosBundleId: 'com.example.annaSakkoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8s4m66v2n4EUHfNSckm8H7T-d-uYfJpU',
    appId: '1:540397899968:ios:29c85e4ce1898f8322dd25',
    messagingSenderId: '540397899968',
    projectId: 'sakkokassa-15fec',
    storageBucket: 'sakkokassa-15fec.appspot.com',
    iosBundleId: 'com.example.annaSakkoa.RunnerTests',
  );
}
